### ISSUE TITLE
Difficulty obtaining correct gringo.so file

### ISSUE THREAD

**Issue by aindilis** [solsword/dunyazad#2]
This system looks great.  I tried for several hours to build it today.  Building clingo from source with cmake did not generate the gringo.so (python support) file.  I obtained it online for libpython3.4 and used an Ubuntu 14.04 VM, but then it complained of missing initgringo symbol.  I was otherwise unable to proceed.  I was wondering if you knew how to create or obtain the gringo.so file or could provide one.

**Comment by solsword** [comment]
If you're on Ubuntu, I *think* you ought to be able to just apt-get install "clingo" and "gringo" and things will work, but I haven't actually touched this system in years so maybe something is broken now ^.^;

My old code might also not be compatible with newer versions of clingo/gringo, but I'm not 100% sure that's an issue. I don't have time during the week, but maybe I'll take a look at things this weekend and see if I can get them working with out-of-the-box clingo/gringo installs and get back to you. Building from source should hopefully not be necessary.

**Comment by aindilis** [comment]
Some friends and I working again on story generation and we were interested if you had an update regarding Dunyazad (which is one of the most capable *seeming* systems out there)?  I did indeed try with Ubuntu 18.04 but still no luck.

**Comment by solsword** [comment]
Hi @aindilis , I just pushed a fresh commit in which I got things working for me on a new computer (a Mac this time instead of my old Linux machine). So hopefully things should be a *little* more robust now? There were a few things that weren't working with the latest versions of clingo/gringo, and some Python errors, as well as the problem that twee (the Twine compiler) has now been superseded by twee2 (for Twine2). The dependencies remain the same, but in case it's useful, here's what I'm using:

1. `clingo --version` is:
```
clingo version 5.3.0
Address model: 64-bit

libclingo version 5.3.0
Configuration: with Python 3.7.0, with Lua 5.3.4

libclasp version 3.3.4 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
Copyright (C) Benjamin Kaufmann

License: The MIT License <https://opensource.org/licenses/MIT>
```
You probably don't need *exactly* that, but you will need Python 3 support, and I have no idea if the default packages come with that. It does look like Ubuntu has at least `gringo` and `clasp` packages available, and one of those two should come with `clingo` (which just combined the grounder and solver). If that doesn't work or doesn't come with appropriate Python support, it looks like you can grab Python-enabled clingo via Anaconda (see instructions here: https://potassco.org/clingo/ under "Packages"). Feel free to let me know specifics if you're still having trouble.

2. `twee2` is version `Twee2 0.5.0`. I got this by running `gem install twee2` although I had a little trouble getting the right ruby version on my computer. On Ubuntu I'd expect `sudo apt-get install ruby` to do that for you just fine.

3. `dot -V` is: `dot - graphviz version 2.40.1 (20161225.0304)` (but this is optional if you add `--no-viz`). Again on Ubuntu I'd expect `sudo apt-get install graphviz` do work.

Finally, a word of caution: I'm glad that the system is "capable-seeming," but as it's author and also someone who has spent years reconstructing another capable-seeming story generation system, Dunyazad is *very* limited. Just getting it working now the stories it generated had a few places where they just didn't make sense, and most of the parts that look good are more due to human authoring effort than any work on the system's part. The one thing that it is good at/for is generating choices where the system can reason about their impact on the player, but it does this in large part by generating very formulaic choices where the impact is mostly obvious. So even though it served its purpose for my dissertation quite well (a tool for exploring the implications of a theory of choice poetics), I wouldn't trust it with the task of creating aesthetically pleasing stories or choices :P

If you do get it working I'd love to hear about it though, because I know that most of these kind of systems are never available outside one specific lab.

**Comment by aindilis** [comment]
Hi @solsword, First off, fantastic work - thank you for making it work again!  Given your updates/instructions I was able to get it working on Debian 9.6 in about 5-10 minutes.  I took the liberty of uploading its output to a site of mine for some collaborators to see: https://frdcsa.org/~andrewdo/projects/dunyazad/

If it's alright with you I am going to go ahead and build a vagrant box/VirtualBox VM for it and host it on this site (with acknowledgements) so that others can enjoy it even after bitrot makes it uninstallable again in a few months-years.

However, you did mention you wrote another story-generation system and it seemed like you were indicating it was less "limited" than Dunyazad.  I think when I read through your papers I remember reading about it but it escapes my memory now - if you don't mind, what is it called and is it available open source? ;)

@logicmoo mentioned that there are ASP-solvers or bindings for such in SWIPL which we use.  We might take a stab at integrating Dunyazad with SWIPL since our systems are mainly centered around that environment.

One of my own particular uses of Dunyazad is for my Free Life Planner system.  You can see that its arching story-lines resemble contingent plans such as here: 

https://frdcsa.org/~andrewdo/writings/homeless-story/flp2-bt.png
https://frdcsa.org/~andrewdo/projects/dunyazad/out/viz.svg

My interest in Dunyazad began with recognizing its similarity to an attempt at prototyping a story generation algorithm here, although you obviously made it much, much further:

https://frdcsa.org/~andrewdo/writings/overview.txt

So again Dunyazad may well currently be very limited for creating aesthetically pleasing stories or choices, but for our purposes in life planning / personal security it might be less constrained.  It certainly is impressive from the point of view of using model checking to satisfy story constraints!

**Comment by solsword** [comment]
I'm glad that you got it to work! I know how much of a pain installing these things can be, and of course you're welcome to set up a virtual machine image; I'd be grateful. The other system that I've worked on is a reconstruction of Minstrel, but that has its own limitations (and I've no idea the state of that software, ironically; I wasn't the lead on that team). That's hosted at:

https://sites.google.com/a/soe.ucsc.edu/eis-skald/download-changelog

but last update was 2013, which is around when I was no longer working on the project, so I'd guess it wouldn't be trivial to revive, even though the point of our work was to revive an even older system (Minstrel) to explore how it worked. Minstrel/Skald works by iteratively revising a story graph using case-based reasoning, and despite what seemed to be promising example output, after reconstructing it we found it to be pretty flawed, hence my warnings to you about Dunyazad, which I'm sure is the same :)

The dependency graph that you liked is actually not produced by logic programming at all, but rather by an iterative process where each node is generated via a clingo run, because solving more than one node at once proved infeasible given all of the logic I put into each. The main focus of the system eventually became the poetics of each choice, so it has lots of logic for guessing how players will perceive a choice based on the possible consequences of each outcome and their likelihoods (with likelihood being a trinary of impossible/possible/likely). For use in your own system, I'd probably advise you to just look into the logic and pull out the bits that you want, rewriting them in SWIPL, and adjusting the parts that need to be adjusted to work with Prolog's search semantics. For the system that reasons about plot graphs, you could also just read through the Python code for that and attempt to port it to Prolog, but that part of the system never got extensive testing or refinement, so I'd guess it would be more useful as an inspiration than as a complete system to use.

The story generation idea that you outline in that .txt file seems intriguing; I like the idea of a story based on reversal of the reader's perception, and in fact that's got good support within the literary tradition as a basis for story construction (as part of research for building Dunyazad I read William Foster-Harris' "The Basic Patterns of Plot" which emphasizes reversal heavily, although it's a bit dated and heavy-handed). Getting there with logic programming will be quite difficult though :)

Anyways, I am glad that you were able to get things working, and feel free to use the code however makes the most sense to you!
